### ISSUE TITLE
No Imlib2 loader for that file format persists on Debian Stable (10.6)

### ISSUE THREAD

**Issue by J-Reis** [gawen947/imlib2-webp#6] opened 2020-11-29 17:08 UTC
This project doesn't have many recent updates and may well be dead. If so, please forgive my post … but for the time being it is still relevant for Debian Stable for which the included imlib2 lacks webp support and no backport is currently available (as far as I can tell). Also still a top search result for 'sxiv webp support'. So hopefully I'm not committing any rage inducing internet faux pas (other than with this unnecessary paragraph of justification, anyway)!

Installed this as instructed in the readme and webp.so shows up in /usr/lib/x86_64-linux-gnu/imlib2/loaders/ as expected. Feh (and other imlib2 based viewers like SXIV) still fails with 'No Imlib2 loader for that file format'. Perhaps relevant, using essentially the same process to add an HEIC loader (https://github.com/vi/imlib2-heic) worked fine. I'm out of my depth troubleshooting this, so any advice (even angrily schooling me on what doc I should have read more carefully) much appreciated.

![2020-11-29_10-41-35am](https://user-images.githubusercontent.com/23666144/100548557-dd733280-3232-11eb-9f0a-3758a861b49f.png)

**Comment by mikoim** [comment] 2020-11-29 23:25
I got the same error on Fedora 32.
> imlib2.x86_64 1.5.1-4.fc32

```dlopen(file, RTLD_NOW | RTLD_LOCAL);``` seems to return NULL.
![image](https://user-images.githubusercontent.com/3958340/100556292-abbaa400-32e4-11eb-9f0b-96bb132907e6.png)

https://fossies.org/d=564/imlib2-1.7.0/src/lib/loaders.c#31

**Comment by gawen947** [comment] 2020-11-29 23:36
The project is not dead. But since it worked fine on my side, I did not see any reason to update it.

I managed to reproduce the problem on Debian. Indeed dlopen() returns NULL because of a missing symbol, that's also what I found with gdb.

A patch is under way, it should be ready in an hour or so.

**Comment by gawen947** [comment] 2020-11-29 23:48
Just pushed a fix to master. Could you please both check that it works on Debian and Fedora?

**Comment by mikoim** [comment] 2020-11-29 23:49
It works! thank you.

**Comment by gawen947** [comment] 2020-11-29 23:51
@J-Reis does it work for you now?

**Comment by J-Reis** [comment] 2020-11-30 00:18
Yep, works perfectly. Couldn't have hoped for a better (or faster) fix, many thanks.

Also, no need to update a feature complete project that works! I'm just gun shy having been told off for posting issues on older projects. Hard for a regular joe to navigate all the prickly etiquette I find … or maybe I'm just dense. Either way, none of that is on you! Thanks again.

**Comment by gawen947** [comment] 2020-11-30 00:39
Thanks for reporting, actually it helps a lot.

Note that compared to the version shipped with the latest version of Imlib2, this one support loading the first frame of animated WebP and is compatible with a broader range of libwebp versions.

**Closed as completed by gawen947** 2020-11-30 00:39 UTC

**Comment by gadicc** [comment] 2020-11-30 08:30
@gawen947 said:

> A patch is under way, it should be ready in an hour or so.

:open_mouth: :clap: :pray:

**Comment by reinierpost** [comment] 2020-12-21 22:57
I just installed this on Ubuntu 18.04 (which is Debian-based). This check in the `Makefile` failed:

```
ifneq ($(.SHELLSTATUS),0)
$(error cannot guess imlib2 version)
endif
```

(it depends on make being at least 4.2 and Ubuntu 18.04 still has make 4.1)
so I took it out, and after `make` and `sudo make install`, my `feh` now loads .webp images. Thanks a bunch!

It would be nice if someone did a PPA for Debian/Ubuntu.
